### ISSUE TITLE
The backing type 'Advanced.CMS.TimeProperty.TimeProperty' is not a registered PropertyDefinitionType

### ISSUE THREAD

**Issue by valdisiljuconoks** [advanced-cms/time-property#10]
Following the tutorial.
Added property, added `Startup.cs` line.
App fails with `The backing type 'Advanced.CMS.TimeProperty.TimeProperty' is not a registered PropertyDefinitionType`.

```
[Display(GroupName = SystemTabNames.Content, Order = 330)]
[CultureSpecific]
[BackingType(typeof(Advanced.CMS.TimeProperty.TimeProperty))]
[TimePropertySettings(TimePattern = "HH:mm")]
public virtual TimeSpan? Time1 { get; set; }
```

![image](https://user-images.githubusercontent.com/1767179/218335236-64e83f38-9436-4a92-9f6e-8db6332bcddd.png)

**Comment by barteksekula** [comment]
Strange, I've just checked on a clean alloy created via CLI tool and it worked fine.
![image](https://user-images.githubusercontent.com/1321664/218423986-47c132b7-2cd4-4776-b63b-a65ced0a5f47.png)

It seems as if Advanced.CMS.TimeProperty.dll was not being scanned for you.

**Comment by valdisiljuconoks** [comment]
2nd run :)

![image](https://user-images.githubusercontent.com/1767179/218840152-77c652dc-146d-47d6-8c39-d96bda324b37.png)
