### ISSUE TITLE
Display local time in time editor

### ISSUE THREAD

**Issue by chrno1209** [advanced-cms/time-property#2]
Hi,
I have a project where editor wants to see local time in time editor, just like in datetime editor.
So db stores UTC time and editors in different time zones can see different times base on their time zone or even if DST is happening (for UK base).

Is it possible to do that in time property?

Thanks.

**Comment by gregwiechec** [comment]
There is no support for local time and time zones.

**Comment by chrno1209** [comment]
Hi @gregwiechec, thanks for the info :)
