### ISSUE TITLE
Dojo error breaking all properties view

### ISSUE THREAD

**Issue by jocuffey** [advanced-cms/time-property#3]
I have one page type using this property and now getting a script error in dojo.js when trying to load all properties view, which just displays blank. Using Episerver CMS v.11.12

**Comment by gregwiechec** [comment]
Hi,
Could you give more details please. Is there something specific on the page type?
Maybe you could also turn on client resources. Then, the exception should contains more information.

**Comment by barteksekula** [comment]
@jocuffey any news on that? could you please try to clone this repo and try on the Alloy demo site (just clone and F5)

**Comment by jocuffey** [comment]
@gregwiechec @barteksekula I uninstalled and reinstalled the nuget package and the issue seems to be resolved. I'll close this.

**Comment by jocuffey** [comment]
Just to add more info - the cause of this issue seemed to be using a demo license from Episerver. When I changed the license to a partner developer license, the dojo errors were resolved.
