### ISSUE TITLE
Not able to use in CMS12 (.Net5)

### ISSUE THREAD

**Issue by Vijaykumarj** [advanced-cms/time-property#5]
Hi Guys,
     I am interesting use this package and it's fulfilling my requirement in my project. But my project is built on CMS12 (i.e .Net5). But it is not compatible with CMS12 and getting Version conflict detected.

Please update the required dependencies to be compatible with CMS12.

	_NU1107	Version conflict detected for EPiServer.CMS.Core. Install/reference EPiServer.CMS.Core 12.0.3 directly to project CMSEmptySite to resolve this issue. 
 CMSEmptySite -> EPiServer.CMS 12.1.0 -> EPiServer.CMS.AspNetCore.HtmlHelpers 12.0.3 -> EPiServer.CMS.AspNetCore.Mvc 12.0.3 -> EPiServer.CMS.AspNetCore.Routing 12.0.3 -> EPiServer.CMS.AspNetCore.Templating 12.0.3 -> EPiServer.CMS.AspNetCore 12.0.3 -> EPiServer.CMS.Core (= 12.0.3) 
 CMSEmptySite -> Advanced.CMS.TimeProperty 1.0.0 -> EPiServer.CMS.Core (>= 11.11.3 && < 12.0.0).	CMSEmptySite	D:\test\CMSEmptySite\CMSEmptySite.csproj	1_	

thanks in advance.

**Comment by barteksekula** [comment]
net5 support will be available soon

**Comment by barteksekula** [comment]
The package is now available https://nuget.optimizely.com/package/?id=Advanced.CMS.TimeProperty&v=2.0.0

**Comment by Vijaykumarj** [comment]
thank you so much barteksekula
